In [36]:
import pandas as pd
dataset= pd.read_csv('drum_noi_sp_new_1.csv')
dataset

,Unnamed: 0,id,datetime,machine,temp,speed,rpm,rms_velocity_x,rms_velocity_y,rms_velocity_z,rms_Acceleration_x,rms_Acceleration_y,rms_Acceleration_z,created_on,updated_on
0,0,5385,01-03-2022 00:00,Drumming 4,41.56,27.94,420.0,4.41,3.94,1.61,98.72,87.96,37.63,2022-03-17 11:00:25,2022-07-27 09:03:49
1,1,5386,01-03-2022 00:01,Drumming 4,41.44,27.94,90.0,4.26,3.81,1.61,95.29,85.17,37.43,2022-03-17 11:00:25,2022-07-27 09:03:49
2,2,5387,01-03-2022 00:02,Drumming 4,41.31,28.00,60.0,4.09,3.74,1.58,91.15,83.66,36.84,2022-03-17 11:00:25,2022-07-27 09:03:49
3,3,5388,01-03-2022 00:03,Drumming 4,41.19,27.97,450.0,3.89,3.66,1.54,86.73,82.04,35.68,2022-03-17 11:00:25,2022-07-27 09:03:49
4,4,5389,01-03-2022 00:04,Drumming 4,41.06,27.97,60.0,3.70,3.50,1.64,82.13,77.90,37.74,2022-03-17 11:00:25,2022-07-27 09:03:49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157728,313293,318678,11/12/2022 05:26:01,Drumming 4,40.19,27.97,300.0,2.44,2.81,1.41,53.13,61.06,30.50,2022-12-11 06:18:42,2022-12-11 06:18:42
157729,313294,318679,11/12/2022 05:27:01,Drumming 4,40.12,27.97,210.0,2.61,2.95,1.48,56.57,63.93,32.13,2022-12-11 06:18:42,2022-12-11 06:18:42
157730,313295,318680,11/12/2022 05:28:01,Drumming 4,40.00,4.59,30.0,3.19,3.55,1.84,69.30,77.15,39.82,2022-12-11 06:18:42,2022-12-11 06:18:42
157731,313296,318681,11/12/2022 05:29:01,Drumming 4,39.94,11.95,30.0,0.39,0.05,0.06,8.00,1.06,1.22,2022-12-11 06:18:42,2022-12-11 06:18:42
157732,313308,318693,11/12/2022 05:41:01,Drumming 4,41.94,21.51,300.0,0.53,0.51,0.38,11.46,11.23,8.14,2022-12-11 06:18:42,2022-12-11 06:18:42

In [33]:
# dataset= dataset.drop(['noise','average_velocity_x','average_velocity_y','average_velocity_z','Average_Acceleration_x','Average_Acceleration_y','Average_Acceleration_z'],axis=1)
# dataset

In [34]:
# dataset= dataset.loc [(dataset['speed']>0) & (dataset['speed']<=35)]
# dataset

In [37]:
dataset.loc [(dataset['speed']>25)& (dataset['speed']<30) & (dataset['rms_Acceleration_x']<180)& (dataset['rms_Acceleration_y']<180) & (dataset['rms_Acceleration_z']<180) ]

,Unnamed: 0,id,datetime,machine,temp,speed,rpm,rms_velocity_x,rms_velocity_y,rms_velocity_z,rms_Acceleration_x,rms_Acceleration_y,rms_Acceleration_z,created_on,updated_on
0,0,5385,01-03-2022 00:00,Drumming 4,41.56,27.94,420.0,4.41,3.94,1.61,98.72,87.96,37.63,2022-03-17 11:00:25,2022-07-27 09:03:49
1,1,5386,01-03-2022 00:01,Drumming 4,41.44,27.94,90.0,4.26,3.81,1.61,95.29,85.17,37.43,2022-03-17 11:00:25,2022-07-27 09:03:49
2,2,5387,01-03-2022 00:02,Drumming 4,41.31,28.00,60.0,4.09,3.74,1.58,91.15,83.66,36.84,2022-03-17 11:00:25,2022-07-27 09:03:49
3,3,5388,01-03-2022 00:03,Drumming 4,41.19,27.97,450.0,3.89,3.66,1.54,86.73,82.04,35.68,2022-03-17 11:00:25,2022-07-27 09:03:49
4,4,5389,01-03-2022 00:04,Drumming 4,41.06,27.97,60.0,3.70,3.50,1.64,82.13,77.90,37.74,2022-03-17 11:00:25,2022-07-27 09:03:49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157725,313290,318675,11/12/2022 05:23:01,Drumming 4,40.31,27.97,180.0,1.70,1.97,1.05,36.75,42.41,22.51,2022-12-11 06:18:42,2022-12-11 06:18:42
157726,313291,318676,11/12/2022 05:24:01,Drumming 4,40.25,27.94,330.0,1.94,2.24,1.14,41.93,48.39,24.48,2022-12-11 06:18:42,2022-12-11 06:18:42
157727,313292,318677,11/12/2022 05:25:01,Drumming 4,40.25,27.97,90.0,2.06,2.46,1.24,44.54,53.32,26.78,2022-12-11 06:18:42,2022-12-11 06:18:42
157728,313293,318678,11/12/2022 05:26:01,Drumming 4,40.19,27.97,300.0,2.44,2.81,1.41,53.13,61.06,30.50,2022-12-11 06:18:42,2022-12-11 06:18:42
157729,313294,318679,11/12/2022 05:27:01,Drumming 4,40.12,27.97,210.0,2.61,2.95,1.48,56.57,63.93,32.13,2022-12-11 06:18:42,2022-12-11 06:18:42

In [27]:
dataset.loc [(dataset['speed']>=5)& (dataset['speed']<10) & (dataset['rms_Acceleration_x']<50)& (dataset['rms_Acceleration_y']<50) & (dataset['rms_Acceleration_z']<50)]

,id,datetime,machine,temp,speed,rpm,rms_velocity_x,rms_velocity_y,rms_velocity_z,rms_Acceleration_x,rms_Acceleration_y,rms_Acceleration_z,created_on,updated_on
47,5432,01-03-2022 00:47,Drumming 4,41.38,8.43,330.0,1.04,1.06,0.57,23.15,23.42,12.97,2022-03-17 11:00:25,2022-07-27 09:03:49
57,5442,01-03-2022 00:57,Drumming 4,40.69,6.32,210.0,0.47,0.49,0.29,10.70,10.99,6.93,2022-03-17 11:00:25,2022-07-27 09:03:49
89,5474,01-03-2022 01:29,Drumming 4,40.50,5.99,180.0,0.67,0.67,0.32,15.34,15.36,8.37,2022-03-17 11:00:25,2022-07-27 09:03:49
203,5588,01-03-2022 03:23,Drumming 4,38.75,9.65,360.0,1.35,1.25,0.68,29.89,27.90,15.91,2022-03-17 11:00:25,2022-07-27 09:03:49
218,5603,01-03-2022 03:38,Drumming 4,41.31,5.93,30.0,0.06,0.12,0.10,1.42,2.51,2.24,2022-03-17 11:00:25,2022-07-27 09:03:49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312732,318117,10/12/2022 20:02:01,Drumming 4,40.69,7.00,240.0,0.14,0.18,0.25,3.19,3.95,5.34,2022-12-10 22:18:12,2022-12-10 22:18:12
312816,318201,10/12/2022 21:26:01,Drumming 4,41.75,9.92,300.0,0.39,0.09,0.05,7.99,1.90,1.05,2022-12-10 22:18:12,2022-12-10 22:18:12
312950,318335,10/12/2022 23:43:01,Drumming 4,42.44,7.84,30.0,0.37,0.08,0.08,7.53,1.72,1.84,2022-12-11 06:18:42,2022-12-11 06:18:42
313084,318469,11/12/2022 01:57:01,Drumming 4,41.12,6.17,60.0,0.38,0.10,0.05,7.87,2.14,1.13,2022-12-11 06:18:42,2022-12-11 06:18:42
313275,318660,11/12/2022 05:08:01,Drumming 4,40.06,8.10,270.0,0.93,0.98,0.58,20.60,21.74,12.74,2022-12-11 06:18:42,2022-12-11 06:18:42

In [49]:
dataset.drop (dataset.loc [(dataset['speed']>0)& (dataset['speed']<5) & (dataset['rms_Acceleration_x']<30)& (dataset['rms_Acceleration_y']<30) & (dataset['rms_Acceleration_z']<30)].index, inplace=True)
dataset

,id,datetime,machine,temp,speed,rpm,rms_velocity_x,rms_velocity_y,rms_velocity_z,rms_Acceleration_x,rms_Acceleration_y,rms_Acceleration_z,created_on,updated_on
52,5460,01-03-2022 01:15,Drumming 4,43.44,30.00,30.0,2.44,2.59,1.07,56.78,63.56,28.29,2022-03-17 11:00:25,2022-07-27 09:03:49
53,5461,01-03-2022 01:16,Drumming 4,43.19,30.00,330.0,2.06,1.95,0.79,49.97,47.26,18.13,2022-03-17 11:00:25,2022-07-27 09:03:49
56,5464,01-03-2022 01:19,Drumming 4,42.50,30.00,30.0,2.17,2.32,0.96,51.60,55.99,21.54,2022-03-17 11:00:25,2022-07-27 09:03:49
60,5468,01-03-2022 01:23,Drumming 4,41.56,30.00,30.0,2.52,2.46,1.43,57.49,57.68,34.27,2022-03-17 11:00:25,2022-07-27 09:03:49
61,5470,01-03-2022 01:25,Drumming 4,41.12,30.00,450.0,1.57,1.83,1.05,36.15,44.58,25.47,2022-03-17 11:00:25,2022-07-27 09:03:49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157701,318610,11/12/2022 04:18:01,Drumming 4,40.38,27.94,60.0,8.84,9.35,5.45,190.75,201.78,117.71,2022-12-11 06:18:42,2022-12-11 06:18:42
157702,318611,11/12/2022 04:19:01,Drumming 4,40.31,27.94,150.0,9.95,10.52,5.94,215.12,227.61,128.44,2022-12-11 06:18:42,2022-12-11 06:18:42
157703,318612,11/12/2022 04:20:01,Drumming 4,40.25,27.94,30.0,10.83,11.48,6.39,234.83,248.92,138.53,2022-12-11 06:18:42,2022-12-11 06:18:42
157704,318613,11/12/2022 04:21:01,Drumming 4,40.25,16.21,60.0,11.58,12.19,6.80,251.99,264.99,147.80,2022-12-11 06:18:42,2022-12-11 06:18:42
157730,318680,11/12/2022 05:28:01,Drumming 4,40.00,4.59,30.0,3.19,3.55,1.84,69.30,77.15,39.82,2022-12-11 06:18:42,2022-12-11 06:18:42

In [13]:
# dataset= dataset.loc [(dataset['rms_Acceleration_x']<=200) & (dataset['rms_Acceleration_y']<=200) & (dataset['rms_Acceleration_x']<=113)]
# dataset

,Unnamed: 0,Unnamed: 0.1,id,datetime,machine,temp,speed,rpm,rms_velocity_x,rms_velocity_y,rms_velocity_z,rms_Acceleration_x,rms_Acceleration_y,rms_Acceleration_z,created_on,updated_on
0,0,0,5385,01-03-2022 00:00,Drumming 4,41.56,27.94,420,4.41,3.94,1.61,98.72,87.96,37.63,17-03-2022 11:00,27-07-2022 09:03
1,1,1,5386,01-03-2022 00:01,Drumming 4,41.44,27.94,90,4.26,3.81,1.61,95.29,85.17,37.43,17-03-2022 11:00,27-07-2022 09:03
2,2,2,5387,01-03-2022 00:02,Drumming 4,41.31,28.00,60,4.09,3.74,1.58,91.15,83.66,36.84,17-03-2022 11:00,27-07-2022 09:03
3,3,3,5388,01-03-2022 00:03,Drumming 4,41.19,27.97,450,3.89,3.66,1.54,86.73,82.04,35.68,17-03-2022 11:00,27-07-2022 09:03
4,4,4,5389,01-03-2022 00:04,Drumming 4,41.06,27.97,60,3.70,3.50,1.64,82.13,77.90,37.74,17-03-2022 11:00,27-07-2022 09:03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173743,178624,313316,318701,11-12-2022 05:49,Drumming 4,41.31,34.02,300,4.88,5.55,3.26,103.85,117.77,68.95,11-12-2022 06:18,11-12-2022 06:18
173744,178625,313317,318702,11-12-2022 05:50,Drumming 4,41.25,33.96,60,4.92,5.59,3.27,104.54,118.55,69.12,11-12-2022 06:18,11-12-2022 06:18
173745,178626,313318,318703,11-12-2022 05:51,Drumming 4,41.06,33.96,30,5.19,5.86,3.42,110.29,124.16,72.60,11-12-2022 06:18,11-12-2022 06:18
173747,178628,313320,318705,11-12-2022 05:53,Drumming 4,40.88,33.99,510,5.28,5.97,3.43,112.42,126.81,72.83,11-12-2022 06:18,11-12-2022 06:18
173749,178630,313322,318707,11-12-2022 05:55,Drumming 4,40.62,33.96,30,5.07,5.66,3.39,107.52,119.67,71.77,11-12-2022 06:18,11-12-2022 06:18

In [39]:
# dataset['Unnamed: 0']
dataset= dataset.drop(['Unnamed: 0'],axis=1)
dataset

,id,datetime,machine,temp,speed,rpm,rms_velocity_x,rms_velocity_y,rms_velocity_z,rms_Acceleration_x,rms_Acceleration_y,rms_Acceleration_z,created_on,updated_on
11,5396,01-03-2022 00:11,Drumming 4,40.50,20.02,390.0,3.07,2.92,1.70,70.11,66.30,40.67,2022-03-17 11:00:25,2022-07-27 09:03:49
12,5399,01-03-2022 00:14,Drumming 4,40.62,4.23,60.0,0.19,0.22,0.17,4.25,4.87,3.64,2022-03-17 11:00:25,2022-07-27 09:03:49
30,5417,01-03-2022 00:32,Drumming 4,40.19,12.07,570.0,2.84,2.98,2.15,64.09,65.92,49.72,2022-03-17 11:00:25,2022-07-27 09:03:49
31,5425,01-03-2022 00:40,Drumming 4,41.69,22.37,420.0,0.81,0.77,0.51,18.62,16.87,11.55,2022-03-17 11:00:25,2022-07-27 09:03:49
38,5432,01-03-2022 00:47,Drumming 4,41.38,8.43,330.0,1.04,1.06,0.57,23.15,23.42,12.97,2022-03-17 11:00:25,2022-07-27 09:03:49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157722,318670,11/12/2022 05:18:01,Drumming 4,40.00,2.80,90.0,0.82,0.91,0.55,18.12,19.98,12.03,2022-12-11 06:18:42,2022-12-11 06:18:42
157723,318673,11/12/2022 05:21:01,Drumming 4,40.12,21.48,30.0,0.43,0.40,0.35,9.47,8.88,7.42,2022-12-11 06:18:42,2022-12-11 06:18:42
157730,318680,11/12/2022 05:28:01,Drumming 4,40.00,4.59,30.0,3.19,3.55,1.84,69.30,77.15,39.82,2022-12-11 06:18:42,2022-12-11 06:18:42
157731,318681,11/12/2022 05:29:01,Drumming 4,39.94,11.95,30.0,0.39,0.05,0.06,8.00,1.06,1.22,2022-12-11 06:18:42,2022-12-11 06:18:42
157732,318693,11/12/2022 05:41:01,Drumming 4,41.94,21.51,300.0,0.53,0.51,0.38,11.46,11.23,8.14,2022-12-11 06:18:42,2022-12-11 06:18:42

In [50]:
dataset.to_csv('drum_noi_sp_new_7.csv')